dist: xenial
sudo: required
services:
- docker
language: go
go:
- "1.13.x"

branches:
  only:
    - master

env:
  global:
    GOFLAGS=-mod=vendor

install:
  - make tools

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    - name: "make lint"
      script: make lint
    - name: "make test"
      script: make test